export const DIJKSTRA = "Dijkstra"
export const ASTAR = "A*"
export const GREEDY_BFS = "Greedy Best First Search"
export const BFS = "Breadth First Search"
export const DFS = "Depth First Search"
export const DSTAR = "D*"

export const RAND_MAZE = "Random Maze"
export const RECURSIVE_DIVISON = "Recursive Division"
export const DRAW_COUNTOUR = "Contour Walls"

export const ADDING_WEIGHT = "Adding Weight"
export const MOVING_TARGET = "Moving Target"
export const MOVING_START = "Moving Start"
export const MOVING_SECOND_TARGET = "Moving Second Target"
export const SETTING_SECOND_TARGET = "Moving Second Target"
export const DELETING = "Deleting"
export const PLACING_WALLS = "Placing Walls"
export const VISUALIZING = "Visualizing"
