export const DIJKSTRA = "Dijkstra"
export const ASTAR = "A*"
export const GREEDY_BFS = "Greedy Best First Search"
export const BFS = "Breadth First Search"
export const DFS = "Depth First Search"
export const DSTAR = "D*"

export const RAND_MAZE = "Random Maze"
export const RECURSIVE_DIVISON = "Recursive Division"
export const DRAW_COUNTOUR = "Contour Walls"
